---
abstract: 'read/write MARC data into JSON format'
author:
  - 'Clay Fouts <cfouts@khephera.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MARC-File-JSON
requires:
  JSON: 2.53
  JSON::Streaming::Reader: 0.05
  MARC::Record: 2
  MARC::Record::Generic: 0.001
version: 0.001
